# ("project", required) Marks this as a Dagster project.
directory_type = "project"

[project]

root_module = {{ project_name }}
code_location_target_module = "{{ project_name }}.definitions"

# (string, optional) Specifies the project submodule where new components and
# definitions are scaffolded.
#
# Defaults to `<root_module>.defs`.
# dg expects it but kedro-dagster just generate a simple definitions.py so we
# use instead the root_module
defs_module = "kedro_dagster_example"

# (string, optional) Specifies the name used for the code location when the project is
# loaded as a code location.
#
# Defaults to the project name (which is usually the # hyphenated variant of
# the root module name).
code_location_name = "{{ package_name }}"

# [cli]

# (bool, optional) Specifies whether to use verbose output.
#
# Defaults to `false`.
# verbose = false

# (list[str], optional) Specifies a list of warning IDs to suppress. Full list of warning IDs can be
# found here: https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-dg-core/dagster_dg_core/utils/warnings.py
# suppress_warnings = [
#     "cli_config_in_workspace_project",
#     "deprecated_user_config_location",
#     "deprecated_python_environment",
#     "deprecated_dagster_dg_library_entry_point",
#     "missing_dg_plugin_module_in_manifest",
#     "project_and_activated_venv_mismatch",
# ]

# For a list of other valid config parameters
# See https://docs.dagster.io/api/clis/dg-cli/dg-cli-configuration
